#!/bin/bash
# declare STRING variable
STRING="Starting No More Pixies"
#print variable on a screen
echo $STRING
#go to directory where this script is located
cd ${0%/*}
#launch the game
python NMP.py
